language: python

python:
  - 3.8

services:
  - mysql

install: pip install -r requirements.txt pytest-cov python-coveralls

before_script:
  - echo "Creating the database..."
  - mysql -uroot < travis_schemas/upgrade.sql
  - python flask db upgrade


script: pytest

after_success: coveralls
