language: python

python:
  - 3.8

services:
  - mysql

install: pip install -r requirements.txt pytest-cov

before_script:
  - echo "Creating the database..."
  - mysql -uroot < travis_schemas/upgrade.sql
  - flask db upgrade
  - python src/database/inserts.py


script: pytest --cov=src tests/

after_success: coveralls -v
