
version: '2'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '5000:5000'

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_USER: db_user
      MYSQL_PASSWORD: qwerty
      MYSQL_DATABASE: department_project