"""update user table

Revision ID: 426f3165462c
Revises: 8010e8c6916a
Create Date: 2021-04-21 14:33:49.557341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426f3165462c'
down_revision = '8010e8c6916a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_address', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_unique_constraint(None, 'user', ['email_address'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'uuid')
    op.drop_column('user', 'username')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'email_address')
    # ### end Alembic commands ###
