"""add departments uuid

Revision ID: e8d7ff69c142
Revises: 95ed901a19fc
Create Date: 2021-05-08 13:28:13.990003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d7ff69c142'
down_revision = '95ed901a19fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'department', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'uuid')
    # ### end Alembic commands ###
